name: Scrape cros-updates-serving

on:
  schedule:
    - cron: "*/15 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Scraping
        run: |
          npm install tabletojson json2csv
          npm run scrape
        env:
          CI: true
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: GitHub Push
        uses: ad-m/github-push-action@v.0.4.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
